root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  data_path: "https://drive.google.com/uc?export=download&id=1b42vrHYnrbUBFNbViep5-YcVLMXy5nlM"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion


model_building:
  root_dir: artifact/model
  train_data_file: artifact/data_ingestion/DATASET/TRAIN
  model: model.pth

model_evaluation:
  root_dir: artifact/model_eval
  test_data_file: artifact/data_ingestion/DATASET/TEST
  model: artifact/model/model.pth
  metrices: artifact/model_eval/metric.json