root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  data_path: "https://drive.google.com/uc?export=download&id=1b42vrHYnrbUBFNbViep5-YcVLMXy5nlM"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion